/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java8.ETL;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
    }
}
